# Generated by Django 5.0.1 on 2024-01-25 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MenuItemAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listmenu',
            old_name='invetory',
            new_name='inventory',
        ),
    ]
