# Generated by Django 5.0 on 2024-01-05 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_menu_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='person_name',
        ),
    ]
