# Generated by Django 5.0 on 2024-01-06 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_person_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('employee_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='myapp.person')),
            ],
        ),
    ]
